### ISSUE TITLE
Support for groupings?

### ISSUE THREAD

**Issue by lukasbIP** [robshakir/pyangbind#12]
Are groupings supported? If not please consider adding the feature.
From my short look at the code i would conclude that groupings are not supported yet.

**Comment by robshakir** [comment]
Hi,

Groupings are essentially just a logical collection of leaves/lists/containers - pyangbind generates classes based on the actual instantiated model (i.e., only when something has a path). 

So, if you have a module that has:

```javascript
module foo-example {
    prefix "foo-ex";

    grouping test-group {
        leaf test-leaf {
            type string;
        }
    }
}
```

then the expected output of '-f pybind' is nothing - since this module does not instantiate the grouping that has been defined. This is in common with the output of other pyang formats (e.g., tree):

```
[~]
(20:14 - s000) corretto> pyang -f tree foo-example.yang
```

If we create one instance of the grouping:

```javascript
module foo-example-one-inst {
    prefix "foo-ex";
    namespace "http://rob.sh/yang/examples/foo-example";

    grouping test-group {
        leaf test-leaf {
            type string;
        }
    }

    container container-one {
        uses test-group;
    }
}
```

Then, both 'pybind' and 'tree' will create an instance of the grouping.

```
(20:16 - s000) corretto> pyang -f tree foo-example-one-inst.yang
module: foo-example-one-inst
   +--rw container-one
      +--rw test-leaf?   string
```

The reason that only instantiated groupings are covered is that essentially leaves are not 'settable' until they have been included somewhere in the module's structure. It also means that where a single grouping is used in two places then we repeat the generated code so that the leaves can be set in both places that they are included.

Do you have a use case which requires being able to generate code for a grouping which is not then instantiated with a 'uses' statement?

Thanks,
r.

**Comment by robshakir** [comment]
Hi,

As this one has been stalled quite a while, I'll close it. Please re-open it if you have a use case for generating code for groupings - and can help me understand how this might fit together.

Cheers,
r.
