### ISSUE TITLE
Leaf metadata?

### ISSUE THREAD

**Issue by marksutherland** [robshakir/pyangbind#16]
Hi,

I'm wondering if pyangbind is likely to be able to provide metadata about leafs, particularly their yang type and constraints. It seems as they are mapped directly to python types there's no obvious way to access this information, other than a mention of the yang type in their doc string. Am I missing something?

Mark

**Comment by robshakir** [comment]
Hi Mark,

The information that you can get is generally made available via the member variables  in the YANGDynClass metaclass:

```
  """
    Wrap an type - specified in the base_type arugment - with
    a set of custom attributes that YANG specifies (or are required
    for serialisation of that object). Particularly:

      - base_type:  the original type - for example, string, int.
      - default:    the YANG specified default value of the type.
      - yang_name:  the YANG name of the type (as opposed to a 'safe'
                    Python version).
      - parent:     the class which this type is a member of in the
                    YANG-specified tree.
      - choice:     The choice branch that this type is a member of.
      - is_{container,leaf}: whether this element is a container or
                             a leaf.
      - path_helper: pyangbind helper class to allow XPATH lookups.
      - supplied_register_path: an override for the path that this
                                object should register to. This is
                                used when an element is a member of
                                a list to add the key attributes to
                                the path.
      - extensions:  The list of extensions that should be stored
                     with the type.
  """
```

This in general does not carry all of the YANG information (`base_type` will store the class that is being wrapped, so this potentially has some of the information). I'm not quite clear of the use case that one would have for having all that information available - since instantiating the type should validate this information internally.

For example, let's say you did want to get the restrictions that are associated with something with a 'pattern' or 'range' argument with it, then you can get some of this info based on the fact that the `RestrictedClass` dynamically generated type stores this information as class variables:

```
>>> from bindings import int_
>>> x = int_()
>>> x.int_container.eightrestricted
0
>>> print x.int_container.eightrestricted._restriction_dict
{'range': [u'-42..10']}
```

In this case `base_type` for YANGDynClass is not interesting at all:

```
>>> print x.int_container.eightrestricted._base_type
<class 'lib.yangtypes.RestrictedClass'>
```

If you wanted to implement this, then you could store something like the member of the class_map dict member which does have all this information along with the base class. I wouldn't really want this to be the default behaviour though unless there's a strong use case for it.

Cheers,
r.

**Comment by marksutherland** [comment]
Ok, to give some context I'm attempting to build a fuzz tester that will generate values based on the type information of YANG fields. I can probably do what I want  with the _base_type, _restriction_dict and _restricted_base_class . Thanks!

**Comment by robshakir** [comment]
Hi Mark,

Ah, no worries -- it would be possible to have more info carried into the generated code if these are not sufficient. One could relatively trivially add a flag that made existing data structures be output. If you're interested in doing that, the `elemtype` dict that is generated during parsing of each element (and then output into the `class_str` during code generation) is what you might want to look at.

 * https://github.com/robshakir/pyangbind/blob/master/pybind.py#L694 -- class_str being output, the loop variable `i` here holds all the derived YANG info.
 * https://github.com/robshakir/pyangbind/blob/master/pybind.py#L974  -- the `elemtype` dict being built.

Cheers,
r.
