### ISSUE TITLE
No way to distinguish between having a default of "False" and having no default

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [robshakir/pyangbind#260]
Due to https://github.com/robshakir/pyangbind/blob/master/pyangbind/lib/yangtypes.py#L939 there is no way to distinguish between leaves that have a default value of False and those that have no default

**Comment by NickRenton** [comment]
I have found the place of this error in serialize.py
```
        elif with_defaults == WithDefaults.IF_SET:
          if element._changed() or element._default == element:
            d[yname] = element
```
In my case, parameter has no a default value (so _default returns False), and type of parameter is int (element is not set and because of its type YANG model returns 0). So 'element._default == element' returns True because of False == 0 is True
and in JSON  I have a lot of unnecessary integer parameters with value 0

**Comment by JoseIgnacioTamayo** [comment]
Closing issues without recent activity
