### ISSUE TITLE
Unable to build module from Cisco-IOS-XE-native

### ISSUE THREAD

**Issue by rgrueebler** [robshakir/pyangbind#276]
Hi everyone

I try to generate a python class from the Cisco-IOS-XE-native yang model. Unfortunately, I get the following error:
```
Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:1798): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:1801): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:3108): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:3164): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:3649): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
Cisco-IOS-XE-ip.yang:3667: error: "Cisco-IOS-XE-ip:native" in the path for Tunnel at Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:3663) is not found
Cisco-IOS-XE-ip.yang:3675: error: "Cisco-IOS-XE-ip:native" in the path for Tunnel at Cisco-IOS-XE-native.yang:2422 (at Cisco-IOS-XE-ip.yang:3671) is not found
Cisco-IOS-XE-native.yang:2444 (at Cisco-IOS-XE-ipv6.yang:405): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ipv6"
Cisco-IOS-XE-native.yang:2444 (at Cisco-IOS-XE-ipv6.yang:430): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ipv6"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:227): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:236): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:666): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:721): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:853): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:915): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:1113): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:1128): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:1161): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
Cisco-IOS-XE-native.yang:2741 (at Cisco-IOS-XE-logging.yang:1176): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-logging"
INFO: encountered (<pyang.error.Position object at 0x7f75f3a3a2d0>, 'XPATH_NODE_NOT_FOUND2', ('Cisco-IOS-XE-native', 'native', 'Cisco-IOS-XE-interfaces'))
FATAL: pyangbind cannot build module that pyang has found errors with.
```

Here is the command I used:
```
pyang --plugindir /usr/local/lib/python3.6/dist-packages/pyangbind/plugin/ -f pybind -o yang_models.py Cisco-IOS-XE-native.yang
```

This is the python and pyang version I use for my tests:
```
root@bf1477474958:/yang/vendor/cisco/xe/1751# pyang --version
pyang 2.4.0
root@bf1477474958:/yang/vendor/cisco/xe/1751# python3 --version
Python 3.6.9
```

Is there a fix or a workaround for that problem?

Thank you
Remo

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Thanks.

**Comment by JoseIgnacioTamayo** [comment]
Closing issue without recent updates.

**Comment by yakubcze** [comment]
This issue is still present in the newest version (

<pre>
(venv) [redacted]$ pyang --plugindir $PYBINDPLUGIN -p ../yang/cisco/vendor/cisco/xe/1693/ -f pybind -o test.py ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:2055 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-interfaces.yang:1017): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-interfaces"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:2055 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-interfaces.yang:1021): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-interfaces"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:2055 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-interfaces.yang:1033): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-interfaces"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:2055 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-interfaces.yang:1348): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-interfaces"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:2055 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-interfaces.yang:2922): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-interfaces"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:2055 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-interfaces.yang:3008): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-interfaces"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:1947 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-ip.yang:226): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:1947 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-ip.yang:1990): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:1947 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-ip.yang:2053): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ip"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:1982 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-ipv6.yang:330): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ipv6"
../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-native.yang:1982 (at ../yang/cisco/vendor/cisco/xe/1693/Cisco-IOS-XE-ipv6.yang:352): warning: node "Cisco-IOS-XE-native::native" is not found in module "Cisco-IOS-XE-ipv6"
INFO: encountered (<pyang.error.Position object at 0x7f667e9d1080>, 'XPATH_NODE_NOT_FOUND2', ('Cisco-IOS-XE-native', 'native', 'Cisco-IOS-XE-interfaces'))
FATAL: pyangbind cannot build module that pyang has found errors with.
</pre>

<pre>
(venv) [redacted]$ pip freeze | grep pyang
pyang==2.6.1
pyangbind==0.8.6
</pre>

<pre>
(venv)[redacted]$ python --version
Python 3.10.12
</pre>

Is there any update to this?

Thanks very much!
