### ISSUE TITLE
YANGList type with string key containing a space char

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#28]
For a YANG type containing a list which has a String Key, the Add and Get function expects a space delimited key string representation.

For example, a list which has a key of a String Value and an Integer value, the add function might expect:

`somelist.add("somekeystring 1")`

This logic breaks when the String key value contains a space

`somelist.add("some key string 1")`

On another note, is it possible for yangtypes.YANGListType.YANGList.add() to return a pointer to the newly created list object? Rather than the key value?

This shortens the following from

`somelist.add("somekeystring 1")`
`newitem = somelist.get("somekeystring 1")`

to be

`newitem = somelist.add("somekeystring 1")`

Thanks,
Mark

**Comment by robshakir** [comment]
Hi Mark,

I just committed a change that both:

1. Makes the enhancement requested here -- the only thing to watch for here is that if you add something to a _keyless_ list, then the behaviour is that you get the key back still (whereas for lists with a key it returns the item).

1. Fixes the issue with using spaces in keys. This is done by specifying add(keyname=keyval) - a concatenated string representation is still used for getitem() - since this is backwards compatible, but a new _item() function is added such that you can retrieve items using the same logic. I don't want to change the existing ```__getitem__``` behaviour because this will make things less nice for cases where there is only a single key.

I won't push this to release yet, so if you could check this out from the current GitHub commit (HEAD@6499f74a492abeaa226f78f41cb76b5854a7b24e), that'd be great.

Thanks,
r.

**Comment by mpainenz** [comment]
Hi Rob,

Just to let you know, I have been trying to test this. I'm new to Git (As well as Python, and YANG), so the task of checking out a commit that's not yet part of the master branch is a bit beyond my current skill level.

Thanks for sorting this out, I'll let you know once I get it tested.

Cheers,
Mark

**Comment by robshakir** [comment]
Hi Mark,

This is on `master`, you should just be able to do:

```python
x.b_list.add(valone=42, valtwo=42)
```

with the current 'master' commit. I'm aiming to release something to PyPI once IETF JSON is finished.

**Comment by mpainenz** [comment]
Hi Rob,

Do I need to regenerate my Class Bindings for this to take effect?

I've given this a try, and I get the following error message:

> Traceback (most recent call last):
>   File "C:/Projects/git/genband-oneems-service/src/main.py", line 18, in <module>
>     endpoint_worker.pull_endpoint(1003, "Test-Endpoint-MPaine", 0)
>   File "C:\Projects\git\genband-oneems-service\src\worker\endpointworker.py", line 42, in pull_endpoint
>     pybind_endpoint_list.endpoint.add(registration_id=registration_id, uport=uport)
>   File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 671, in add
>     self.__set(**keyargs)
>   File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 615, in __set
>     key(keydict[kn], load=True)
> TypeError: _set_registration_id() got an unexpected keyword argument 'load'

Code was as follows:

```
        pybind_endpoint_list.endpoint.add(registration_id=registration_id, uport=uport)
        #pybind_endpoint_list.endpoint.add("%s %s" % (registration_id, uport))
        pybind_endpoint = pybind_endpoint_list.endpoint["%s %s" % (registration_id, uport)]
```

Thanks,
Mark

**Comment by mpainenz** [comment]
I have regenerated my class bindings, and this now works as expected.

Thanks Rob,
Mark
