### ISSUE TITLE
Generating netconf request from the classes

### ISSUE THREAD

**Issue by arpp** [robshakir/pyangbind#36]
Hi Rob,
I see that currently there is no support for generating netconf request from generated classes. Is there any plans to add that support?

Thanks,
Arpit

**Comment by robshakir** [comment]
Hi Arpit,

At the moment, pyangbind doesn't have any module that can transform a class structure into a NETCONF transaction. @vnitinv was looking at some southbound support, but I have not yet seen anything on this.

There are a couple of questions around this:

 * What serialisation format does your device expect? It would be possible to use the YANGPathHelper to serialise into XML in a relatively easy way if you need this serialisation. Otherwise, there needs to be some stability around what JSON serialisations will be used (the one that the code currently uses is not documented clearly anywhere).
 * I would envisage that this is a some helper that wraps pyangbind classes, like lib/serialise. Is this what you were envisaging? The actual NETCONF implementation would probably be something like ncclient.

Cheers,
r.

**Comment by arpp** [comment]
Hi Rob,

I am familiar with ncclient and want to use pyangbind in conjunction with it. Currently in ncclient we write xml templates and fill the tags and send the request. 

For example:

template = """<config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <aaa xmlns="http://tail-f.com/ns/aaa/1.1">
  <authentication> <users> <user xc:operation="delete">
  <name>%s</name> </user></users></authentication></aaa></config>"""

m.edit_config(target='candidate', config=template % name)

I was envisaging a use case where I use the classes generated by pyangbind in order to generate these kind of xml which I can use in ncclient to send get/edit requests. This should be similar to json serialisation that is under lib/serialise.

Regards,
Arpit

**Comment by robshakir** [comment]
Hi Arpit,

Indeed, that would be the way to do this. `lib.xpathhelper` might really help you here, since when `--use-xpathhelper` is used as a command-line switch, and a `YANGPathHelper` is provided, then pyangbind maintains a pseudo-XML document internally so that XPATH expressions can be handled.

This is a `lxml.etree` instance, which starts with an element called `root`. You can see it by calling `yang_path_helper_instance.tostring(pretty_print=True)`. Essentially, it looks something like:

```xml
<root>
  <test obj_ptr="ee615914-d975-11e5-910f-acbc32aad1a5">
    <number-range obj_ptr="ee62ffdc-d975-11e5-93ac-acbc32aad1a5"/>
    <ll obj_ptr="ee630c63-d975-11e5-a043-acbc32aad1a5"/>
    <number obj_ptr="ee631378-d975-11e5-a29e-acbc32aad1a5"/>
  </test>
  <load-one obj_ptr="ee631a38-d975-11e5-a78c-acbc32aad1a5">
    <item obj_ptr="ee631f80-d975-11e5-8a62-acbc32aad1a5"/>
  </load-one>
  <load-two obj_ptr="ee6329d9-d975-11e5-b5a4-acbc32aad1a5">
    <item obj_ptr="ee6332c2-d975-11e5-bceb-acbc32aad1a5"/>
  </load-two>
</root>
```

The `obj_ptr` attribute is a key that is used in a dictionary named `_library` of the same class. This provides a pointer to the pyangbind class that represents that element. To write a serialiser, one really just needs to take elements that are leaves, and translate those across to their actual value, I think.

Here's a 5-min PoC:

```python
from pyangbind.lib.xpathhelper import YANGPathHelper
from tmp import test
import copy
from lxml import etree

p = YANGPathHelper()
t = test(path_helper=p)

print p.tostring(pretty_print=True)

new_tree = copy.deepcopy(p._root)

for elem in new_tree.iter("*"):
    if "obj_ptr" in elem.attrib:
        if p._library[elem.attrib["obj_ptr"]]._is_leaf:
            elem.text = unicode(p._library[elem.attrib["obj_ptr"]])
        else:
            pass
        del elem.attrib["obj_ptr"]

print etree.tostring(new_tree, pretty_print=True)                                                  
```

This outputs:

```xml
<root>
  <test>
    <number-range>0</number-range>
    <ll/>
    <number>0</number>
  </test>
  <load-one>
    <item>0</item>
  </load-one>
  <load-two>
    <item>0</item>
  </load-two>
</root>
```

There are a few things that would need to be fixed -- for example, this doesn't handle leaf-lists correctly (see the `ll` element) and one would want to get rid of the `root` element. Also, it needs some functions that are just on the `ietf-json` branch right now to get the namespaces correct.

I'd be happy to assist/review a pull-req for this functionality if you have interest in working on it.

Cheers,
r.

**Comment by vnitinv** [comment]
@arpp Hi Arpit,

I was supposed to work on south bond APIs but got occupied by some other urgent tasks. 
We can work together on this feature.
Do let me know if you want to chat or have a call.

Thanks
Nitin Kr

**Comment by Pathjana** [comment]
I am just starting on PYang and Netconf and was looking at options of xml serializer. Is this some work that is in progress, or if not is it something that I can get some help in doing? I would be able to spend time on this but am not familiar here, so may need some help?

**Comment by robshakir** [comment]
Hi @Pathjana,

There is not currently a work in progress, but to kick start this effort, I'll create a branch with a semi-working implementation and some comments in it as to how it works. If you'd like to sync up to discuss it, please let me know - or feel free to ask questions here.

I'll update the issue once I've created the branch.

Best,
r.

**Comment by robshakir** [comment]
See 6a02282, an initial XML serialisation set of code.

**Comment by JoseIgnacioTamayo** [comment]
Closing this issue as https://github.com/robshakir/pyangbind/issues/122 is closed.
