### ISSUE TITLE
Quirky REST API behavior - Unions

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#40]
Hi Rob,

The Yang model I'm using, makes use of [ietf-inet-types](http://www.netconfcentral.org/modules/ietf-inet-types), specifically the ip-address type, which is a union of either an ipv4 address, or an ipv6 address.

I can import and generate class bindings OK, setting or getting an IP-Address is no problem.

I've however noticed that the REST API I'm communicating with is passing this object in a strange way when passing JSON. Let me provide an example, but first, here is the relevant YANG

Yang definitions:
---

(Please note, prefix, namespace, descriptions and other non-relevant items have been omitted)

File: ietf-inet-types.yang
```
module ietf-inet-types {
  typedef ip-address {
    type union {
      type inet:ipv4-address;
      type inet:ipv6-address;
    }
  }

  typedef ipv4-address {
    type string {
      pattern
        '(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}'
      +  '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
      + '(%[\p{N}\p{L}]+)?';
    }
  }

  typedef ipv6-address {
    type string {
      pattern '((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}'
            + '((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|'
            + '(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\.){3}'
            + '(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))'
            + '(%[\p{N}\p{L}]+)?';
      pattern '(([^:]+:){6}(([^:]+:[^:]+)|(.*\..*)))|'
            + '((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?)'
            + '(%.+)?';
    }
  }

}
```

File: sbc-common.yang
```
module sbc-common {
  import ietf-inet-types {
    prefix inet;
  }

  grouping ip-address {
    leaf ip-address {
      description
        "An IPv4 or IPv6 address.";
      type inet:ip-address;
    }
  }

}
```

File: endpoints.yang
```
module endpoints {
  grouping endpoint-list {
    list endpoint {
      uses sbc-common:ip-address {
        refine "ip-address" {
          description
            "The IPv4 or IPv6 address of the endpoint.";
        }
      }
    }
  }
 
}
```

Binding Class definitions:
---

Here is the IP Address declaration in the endpoint `__init__` function

```
self.__ip_address = YANGDynClass(base=[RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}),RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'}),], is_leaf=True, yang_name="ip-address", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='<omitted>', defining_module='sbc-common', yang_type='inet:ip-address')
```

And here is the Setter method:

```
  def _set_ip_address(self, v, load=False):
    try:
      t = YANGDynClass(v,base=[RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}),RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'}),], is_leaf=True, yang_name="ip-address", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://genband.com/sbc/sbc-common', defining_module='sbc-common', yang_type='inet:ip-address')
    except (TypeError, ValueError):
      raise ValueError("""ip_address must be of a type compatible with base=[RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}),RestrictedClassType(base_type=unicode, restriction_dict={'pattern': u'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'}),], is_leaf=True, yang_name="ip-address", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://genband.com/sbc/sbc-common', defining_module='sbc-common', yang_type='inet:ip-address'""")
    self.__ip_address = t
    if hasattr(self, '_set'):
      self._set()
```

JSON issues:
---

The trouble comes with the API end, and how it passes IP Address information back and forward.

What I might have expected out of a REST/JSON API, would be something like:
```
"ipAddress": "10.64.1.101"
```

Instead what I am seeing is the following:
```
"ipAddress": {
	"ipv6Address": null,
	"ipv4Address": "10.64.1.101"
}
```

Even if I can manage to massage the data when deserializing this, I don't see how I could serialize this back to JSON, and know which type of IP-Address is in use. 

In the class bindings, is there a way to figure out which union type is in use?

I'm not sure what approach to take here. I could fudge things a bit, and manually work out what IP Address type is in use, and tweak the JSON values before serialization/deserialization..  however I'd pefer a way to identify which IP Address is in use via the Class Bindings object.

I hope I'm not missing something more obvious, or some other better way to remedy this situation.

Any Ideas?

Thanks,
Mark

**Comment by robshakir** [comment]
Sorry Mark, I've not had a chance to look at this. I'll try take a look tomorrow.

r.

**Comment by mpainenz** [comment]
No worries Rob, no hurry at all :+1:

**Comment by robshakir** [comment]
Hi Mark,

I'd say that this is quite a broken approach to using `union`. There is nothing defined as `ipv6Address` anywhere, so I'm not clear how one could actually figure out that `ipv6Address` means `inet:ipv6-address`. PyangBind also doesn't actually know that this is the relevant `typedef` either - as you can see, it has already expanded this out into a single `RestrictedClass`. 

Today - the code does not generate any kind of static types - e.g., `Enum` classes for enumerations, or `typedef` statements. This is at the expense of generating them each time they are needed (as basically PyangBind makes all types immutable). The only way that I can think that you would be able to do this is:

 * For every union type find the corresponding entries in the `class_map` dictionary.
 * Make the `base` argument to `YANGDynClass` take a dictionary rather than a list - this would need to be done for unions and anything else that can appear in that list with >1 entry too. This dictionary would e of the form` {'typename': <definition>}`.
 * When setting the value, store the key of the dictionary in some new variable in the `YANGBaseClass` meta-class, such that you can access it at serialisation time.
 *  You would also need to store all the keys of all the dictionaries that you had [0] such that you could set these to `None`.
 * Implement a custom `serialiser` class that now looks specifically at `union` types and does this serialisation.

This is quite a lot of work for something that's not  part of any standard, and quite broken. It seems to me that the API should use a `container` here rather than a `union` since it's trying to include both leaves. Programatically, it does not seem trivial to generically map from the name of the `typedef` into these names; plus it's not clear to me what one does in this case:

```yang
leaf example {
   type union {
     type int8 {
        range "1..2";
     }
     type int8 {
       range "4..8";
    }
  }
}
```

I'm going to (rudely) close this issue as `wontfix`; I don't expect many folks to do this - as it's in clear violation of the specification of a `union` type.

Feel free to re-open if there are further questions.

Cheers,
r.

[0]: In the case that you have a union that includes another union then you'd need to do something like:

```python
def find_all_keys(d, current_keys=[]):
  current_keys.expand(d.keys())
  for k, v in d.iteritems():
    if isinstance(v, dict):
      find_all_keys(v, current_keys=current_keys)
 return current_keys
```

This would find all the keys in nested dictionaries, as well as the top level dictionary.

**Comment by mpainenz** [comment]
Thanks Rob, this confirms my suspicions that it's really an API implementation issue. Thanks for taking the time to look at this.

I'm more than happy to leave this issue here, and I hope that no one else runs into an API that does this, as it's a real pain in the neck, and really defeats the purpose of unions (which themselves are a great idea)

I agree wholeheartedly that there's no point to changing anything in Pyangbind, I was mostly after your opinion to verify that my thought process is correct (that this is a broken implementation), and perhaps a little nudge in the right direction if there was a simple approach to get around it. Clearly there isn't a simple and generic way to get the information required out of Pyangbind, and as you point out, even if you could, it won't work in all cases as per your example.

I think I'm going to take the path of least resistance here, and hard code some rules in to evaluate the difference between IP4/IP6 addresses. I should be able to copy/paste some of the class binding code that Pyangbind has already generated to achieve this task. Thankfully most of the other unions are not overly difficult to evaluate in a similar way. 

I already manipulate JSON post serialization (rather than modifying the serializer class). I chose this approach to solve another API quirk so that I could avoid modifying/branching the project. I will do the same here and insert the required dict items post serialization.

Thank you again for taking the time to look at this, especially since this is not really an issue with pyangbind as such.

Best regards,
Mark
