### ISSUE TITLE
Bindings for Augment keyword are not generating

### ISSUE THREAD

**Issue by rmahidhar** [robshakir/pyangbind#60]
I'm using yang files - turing_machine.yang and second_tape.yang under doc/tutorials/examples at https://github.com/mbj4668/pyang.git for generating python bindings, and observed that pyangbind plugin is not generating bindings for yang files that have augment keyword. Below is the generated bindings for the second_tape.yang that augments turning_machine.yang. Is this intentional or is it a bug? Any input on this issue will be of great help.   

class second_tape(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module second-tape - based on the path /second-tape. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  pass

**Comment by robshakir** [comment]
Hi,

This is expected behaviour - pyangbind only builds classes for instantiated schema nodes, not for logical groupings. 

The bindings are generated in the schema where they are actually instantiated - that is to say the turing machine module itself will have the `tape-content-2` etc. leaves added, rather than them being generated for `second_tape`.

Incidentally, the same is true for a `grouping`. Bindings are generated only when a `uses` statement references a grouping.

If you have further questions, please re-open the issue.

Regards,
r.
