### ISSUE TITLE
Help with RestrictedClassType/YANGBaseClass

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#67]
Hi Rob,

I've got a snippet of code, which takes a generic bindings object, and tries to determine an appropriate SQL Datatype to use for it. The code is roughly based on the JSON Serialiser functionality. Or at least, an older iteration of that code.

The code takes a `PybindBase` decendant, and attempts to map a SQL datatype...

```
    # Key definition
    self.is_key_val = obj._is_keyval

    # Column data type
    if hasattr(obj, "_pybind_base_class"):
	# Special Data Type, could include constraints
	pybind_type = getattr(obj, "_pybind_base_class")
	if pybind_type == "pyangbind.lib.yangtypes.RestrictedClass":
	    pybind_type = getattr(obj, "_restricted_class_base")[0]
    else:
	pybind_type = obj.__name__

    if pybind_type in ['int', 'long']:
	self.mapped_type = "Integer"
    # TODO
    # elif pybind_type in ["pyangbind.lib.yangtypes.RestrictedPrecisionDecimal"]:
    #     self.mapped_type = "Float"
    elif pybind_type in ["pyangbind.lib.yangtypes.YANGBool"]:
	self.mapped_type = "Boolean"
    elif pybind_type == "unicode":
	self.mapped_type = "Unicode"
    # TODO
    # elif pybind_type in ["bitarray.bitarray", "lib.yangtypes.ReferencePathType"]:
    #     self.mapped_type = "None" #to-do
    else:
	raise Exception('Unmapped PyangBind Type Encountered: ', pybind_type)
```

This all works fine, and I'm now trying to see if I can improve this to include a maximum column size in the case of restricted values.

Case in point, 

```
leaf registration-id {
  description "The registration-id of the default destination endpoint.";
  type string {
    length "1..67";
  }
}
```

```
self.__registration_id = YANGDynClass(base=RestrictedClassType(base_type=unicode, restriction_dict={'length': [u'1..67']}), is_leaf=True, yang_name="registration-id", parent=self, choice=(u'selection', u'use-endpoint-default-server'), path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://genband.com/acs', defining_module='acs', yang_type='string', is_config=True)
```

I have a difficult time with the YANGDynClass definitions, and how one can inspect them during run-time. My debugger (PyCharm Community Edition) seems to show me very little when I attempt to inspect these.

![image](https://cloud.githubusercontent.com/assets/16472288/15103027/9c580234-15fa-11e6-8657-b745a3012a2b.png)

I'm curious what information I might be able to pull out at run-time that might help me, such as the restriction-dict relating to the pybinding element.

I hope this makes sense, 

Thanks,
Mark

**Comment by robshakir** [comment]
Hi Mark,

You can see which elements are stored with the class by running `dir()` on the object. I'm not familiar with your IDE, but it might be worth checking if it can give you this output.

```python
>>> dir(h.int_)
['_RestrictedClass__check', '_YANGBaseClass__generate_extmethod', '__abs__', '__add__', '__and__', '__class__', '__cmp__', '__coerce__', '__delattr__', '__dict__', '__div__', '__divmod__', '__doc__', '__float__', '__floordiv__', '__format__', '__getattribute__', '__getnewargs__', '__hash__', '__hex__', '__index__', '__init__', '__int__', '__invert__', '__long__', '__lshift__', '__mod__', '__module__', '__mul__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', '_add_metadata', '_base_type', '_changed', '_choice', '_default', '_defining_module', '_extensions', '_extensionsd', '_extmethods', '_is_config', '_is_container', '_is_keyval', '_is_leaf', '_mchanged', '_metadata', '_namespace', '_parent', '_path', '_path_helper', '_pybind_base_class', '_pybind_generated_by', '_register_path', '_register_paths', '_restricted_class_base', '_restricted_int_size', '_restriction_dict', '_restriction_tests', '_set', '_supplied_register_path', '_yang_name', '_yang_path', '_yang_type', 'append', 'bit_length', 'conjugate', 'default', 'denominator', 'extend', 'getValue', 'imag', 'insert', 'numerator', 'pop', 'real', 'remove', 'yang_name']
```

`_restriction_dict` can be accessed directly from this object - but this won't be something that is reliable in all cases (e.g., `RestrictedClassType` actually wraps itself sometimes to support inheritance).

It seems to me that using the PyangBind output here is probably not optimal - since I would imagine that you're not creating the table in the database at every run of the code. It would seem more optimal to try and build something that directly parses the YANG to figure out a schema for the database, since YANG itself is describing a schema (albeit one that might not be easily mappable to SQL).

An alternative would be - if using PostgreSQL at least - to simply store a Path,JSON blob output - since the data instance is already validated.

Cheers,
r.

**Comment by mpainenz** [comment]
Hi Rob, thanks for the pointer, I'll give that a shot.

I agree that defining a DB Schema directly from Yang would provide a better source for the type of information required to build a DB.

Building the DB Schema from the Bindings had a couple of advantages for me, one of which is that it makes building a serialization process quite simple.

Perhaps there is some way I can make the best of both worlds, and reference both the Yang model, and the Bindings class. But I admit I'm a bit out of my depth when it comes to leveraging Pyang functionality.

I hear what you are saying about storing data in blob format, however if I am understanding correctly, this would mean that the data would be stored in a format which makes writing SQL queries against the data difficult. Because the data in each field may be a collection of fields, rather than an individual data element.

As it stands now, I have a class which can take a pyangbind object, and import/convert it into a SQL database schema (leveraging an ORM, in this case SQLAlchemy, but Django would be possible too). A single Pyangbind object might require several tables, with foreign keys... and it works that all out. On top of that, it will serialize pyangbind objects into the database and back.

I'd quite like to share this code once I have completed it. I hope that it might come in handy for anyone else dealing with large models which require a detailed SQL database.

**Comment by robshakir** [comment]
Understood. I guess the problem you'll have here is that the translation into the `lib.yangtypes` object is not always going to maintain all information. For example, if you have a `uint64` that subsequently has another set of restrictions - then there's nothing that ensures that all the information from the more restricted class is available to someone examining the class. It's possible to add it, but it also means making the types that are generated more complex to ensure that they are always transparent down to the last value. I'd question whether this optimisation is actually worth it.

In terms of storing as a JSON object in a database - Postgres has a cool set of features since it has a way that one can structure some queries against a field that is defined as `jsonb`. For example, see http://www.postgresql.org/docs/9.4/static/functions-json.html or http://schinckel.net/2014/05/25/querying-json-in-postgres/.

I'd definitely be interested in seeing the SQL schema that you've generated/the tooling once you're done!

r.

**Comment by mpainenz** [comment]
I'm impressed with that Postgres functionality. Looking around it seems there is similar JSON field types in a few other more recent DB's too. That will be handy.

Thanks for your comments on the viability of including this information in the bindings. I agree that it's unlikely to be worth the effort, and perhaps a little bit bloating. I have included some basic functionality to allow field-lengths to be set manually after translating a bindings object into a schema. It's not really a big issue, but without this intervention it defaults to some potentially inefficient datatypes such as `nvarchar(max)`, where an `nvarchar(20)` would do. Not the end of the world.

This tool could be quite useful as a starting point, for which manual tweaking could be done after the schema has been generated, and a SQL DB created.

I will create a public repository for this with some documentation, and let you know when that's online.

Cheers,
Mark
