### ISSUE TITLE
Documentation Updates for XPathHelper [was Bug accessing elements using obj['key'] scheme]

### ISSUE THREAD

**Issue by lgifre** [robshakir/pyangbind#73]
Hi Rob,

In the application I'm developing, I need to navigate through a datastore using a path that is not known in advance. Then, when an object is found, I need to modify that object. To implement this functionality I considered using a scheme such as that proposed by you in the tutorial: obj["local-routes"]["static-routes"]["static"]["192.0.2.1/32"]. However, this scheme reports an exception.

Let me illustrate what I want to do with an example:

Assume we have the next simple model:

```
module local-routing {
  namespace "urn:local-routing:local-routing";
  prefix "t";
  container local-routes {
    list static {
      key prefix;
      leaf prefix { type string; }
      leaf next-hop { type string; }
    }
  }
}
```

We generate the Python bindings using:

```
export PYBINDPLUGIN=`/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'`
pyang -V --plugindir $PYBINDPLUGIN -f pybind -o local_routing.py local-routing.yang
```

Assume that we pre-loaded the datamodel using the next code:

```
from local_routing import local_routing
import pyangbind.lib.pybindJSON as pybindJSON
lr = local_routing()
rt1 = lr.local_routes.static.add("192.0.1.0")
rt1.next_hop = "192.0.0.1"
```

So a dump with `print pybindJSON.dumps(lr, filter=False)` reports:

```
{
    "local-routes": {
        "static": {
            "192.0.1.0": {
                "next-hop": "192.0.0.1", 
                "prefix": "192.0.1.0"
            }
        }
    }
}
```

Then, given an input path in a string variable, split the route into its parts and adapt the names to your internal representation:

```
path = "/local-routes/static/192.0.1.0"
pathHops = path.split('/')
pathHops = filter(lambda x: len(x) > 0, pathHops)
pathHops = map(lambda x: x.replace('-', '_'), pathHops)
print pathHops # reports: ['local_routes', 'static', '192.0.1.0']
```

Then starting from the root, we navigate to the desired element:

```
ptr = lr # lr is the root object in the pre-loading code
for pathHop in pathHops:
  ptr = ptr[pathHop]
```

This code reports the next Exception:

```
Traceback (most recent call last):
  File "Main.py", line 21, in <module>
    ptr = ptr[pathHop]
  File "/usr/local/lib/python2.7/dist-packages/pyangbind/lib/base.py", line 88, in __getitem__
    return element()
TypeError: 'YANGBaseClass' object is not callable
```

I think the problem is with that `()` in `return element()`. I tried removing such `()` and seems to work, but I do not know whether I'm breaking some other things.

Could you confirm that it is a bug and that is the right way to navigate through the datastore?

TIA.
Lluis

**Comment by robshakir** [comment]
Hi Lluis,

The example of `obj["x']["y"]["z"]` is suggested solely for when the object has already been output to some interim format - for example, the nested dictionaries that are retrieved by the `obj.get()` function - I don't think this will help you.

The easiest way to do this is to use the `path_helper` argument when initialising the first class. This then makes each object register itself at the path, and you can then retrieve it using the `path_helper.get(path)` syntax. 

The documentation for how this works is at http://pynms.io/pyangbind/xpath/.

What you've reported here isn't a bug - not all attributes that you can retrieve are callable - this is only something that is true of functions. You can usually get the object in a better way by using the `_get_X()` getter on the penultimate object. An example of this is used in `lib.serialise` - see an example here: https://github.com/robshakir/pyangbind/blob/master/pyangbind/lib/serialise.py#L427-L432

To replace the name you should use `safe_name` from `pyangbind.lib.yangtypes` since this will give you consistently what PyangBind will use for a particular YANG name.

LMK if the XPATH documentation linked to above is unclear.

Cheers,
r.

**Comment by lgifre** [comment]
Hi Rob,

The XPATH `path_helper` class is exactly what I was looking for. Thank you so much!
BTW, I was reading the XPATH documentation and I think it is clear to me. The only unclear part is that you provide a model in the "Overview" section, but a different model (not provided) is used in the examples. A reference to the model used in the example could help the reader to understand and try the examples.

I think we can close this issue. Thanks!

Cheers,
Lluis

**Comment by robshakir** [comment]
Lluis,

Good point, thanks! The model used here is simply OpenConfig-BGP - so it's pretty easy to create this as a code example. I'll re-open this issue just to note that I should do that.

Thanks,
r.

**Comment by lgifre** [comment]
Hi again Rob,

I forgot to recommend another enhancement.
Checking the internal XML file generated by the `xpathhelper` class, the attributes that can be used to filter within XPATH expressions are those part of list's keys, right? I think this should be specified in the documentation.

Cheers,
Lluis

**Comment by JoseIgnacioTamayo** [comment]
Closing issues without recent activity
