### ISSUE TITLE
YANG Notifications

### ISSUE THREAD

**Issue by lgifre** [robshakir/pyangbind#75]
Hi Rob!

I found in your web page that pyangbind supports YANG RPCs (http://pynms.io/pyangbind/rpc/), but I couldn't found anything about YANG notifications (https://tools.ietf.org/html/rfc6020#section-4.2.10). Does it has any module dealing with YANG notifications?

In my app I need to issue/receive notifications and will be helpful to have mechanisms to easily generate and parse them in a similar way than that used in RPCs to generate inputs (http://pynms.io/pyangbind/rpc/#exinput) and to parse outputs (http://pynms.io/pyangbind/rpc/#exoutput).

Could it be possible to implement the corresponding structures for that, also reading the models from the YANG files? If you need help testing those functionality, let me know! I can help you on that!

TIA,
Lluis

**Comment by robshakir** [comment]
Hi Lluis,

You're right, today Notifications are not supported in PyangBind. Since the efforts thus far have been focused towards OpenConfig models (where notifications are not used in preferences to a pub/sub model around the models) - then there's been little need.

I'll add supporting these to the backlog.

Cheers,
r.

**Comment by lgifre** [comment]
Hi Rob!

I did some hacks in PyangBind to add support for Notifications.
I sent a pull request with the changes.

Best,
Lluis

**Comment by robshakir** [comment]
Great, thanks Lluis! I merged the change today.

Cheers,
r.
