### ISSUE TITLE
Resolving nested typedefs

### ISSUE THREAD

**Issue by aashaikh** [robshakir/pyangbind#8]
When testing pybind against the OpenConfig routing policy models, there is a problem resolving one of the complex union types (that has a dependency on external YANG modules)
```
could not find a match for tag-type type
could not find a match for pt:tag-type type
...
TypeError: could not resolve typedefs ['tag-type', 'pt:tag-type']
```
the type in question (in policy-types.yang): 
```
typedef tag-type {
    type union {
      type uint32;
      type yang:hex-string;
    }
    description "type for expressing route tags on a local system,
    including IS-IS and OSPF; may be expressed as either decimal or
    hexidecimal integer";
    reference
      "RFC 2178 OSPF Version 2
      RFC 5130 A Policy Control Mechanism in IS-IS Using
      Administrative Tags";
  }
```

the hex-string type is in ietf-yang-types
```
typedef hex-string {
    type string {
      pattern '([0-9a-fA-F]{2}(:[0-9a-fA-F]{2})*)?';
    }
    description
     "A hexadecimal string with octets represented as hex digits
      separated by colons.  The canonical representation uses
      lowercase characters.";
  }
```

I'm not yet familiar with the plugin's type processing, but it seems this type is not found in the list passed to build_typedefs()

**Comment by robshakir** [comment]
If you specify policy-types.yang on the list of modules on the cli this will resolve. There is an issue with how paying loads the module includes - I am working on a patch to send to Martin. 

r.

**Comment by robshakir** [comment]
@aashaikh - can you retest this please? d4830f109763a6c618b64b2f6a8e18d9f5174d4 should resolve this.

**Comment by aashaikh** [comment]
Thanks -- this fixed the error with the policy module.  But when I add bgp.yang, we get a similar error:
```
pyang --plugindir ~1 --strict bgp/bgp.yang policy/routing-policy.yang -p policy -p bgp -p ~/workspace/yang -f pybind
```
gives
```
could not find a match for bgp-well-known-community-type type
could not find a match for bgp-types:bgp-well-known-community-type type
...
TypeError: could not resolve typedefs ['bgp-well-known-community-type', 'bgp-types:bgp-well-known-community-type']
```
Adding bgp-types.yang to the pyang line didn't seem to make a difference.  This type is a plain identityref:
```
  typedef bgp-well-known-community-type {
    type identityref {
      base bgp-well-known-std-community;
    }
    description
      "Type definition for well-known IETF community attribute
      values";
    reference
      "IANA Border Gateway Protocol (BGP) Well Known Communities";
  }
```
I think you're familiar with this identity -- we changed it recently from an enum.

**Comment by robshakir** [comment]
Embarrassing! This was something that I guess is not used elsewhere, since the identityref is generally just directly used, rather than via a typedef. I've resolved this in fbdda66. PTAL (and thanks for the patience!)

**Comment by aashaikh** [comment]
it's interesting that when i try the interfaces model (which depends on ietf-yang-types) , it can't resolve a typedef with an identityref that points directly to the base type. 

in the model:
```
 identity interface-type {
    description
      "Base identity from which specific interface types are
       derived.";
    reference
      "RFC 7223: A YANG Data Model for Interface Management";
  }
```
usage in the model:
```
leaf type {
      type identityref {
        base interface-type;
      }
      mandatory true;
      description
        "[adapted from IETF interfaces model (RFC 7223)]

        The type of the interface.

        When an interface entry is created, a server MAY
        initialize the type leaf with a valid value, e.g., if it
        is possible to derive the type from the name of the
        interface.

        If a client tries to set the type of an interface to a
        value that can never be used by the system, e.g., if the
        type is not supported or if the type does not match the
        name of the interface, the server MUST reject the request.
        A NETCONF server MUST reply with an rpc-error with the
        error-tag 'invalid-value' in this case.";
      reference
        "RFC 2863: The Interfaces Group MIB - ifType";
    }
```
gives the following error:
```
FATAL: identityref with an unknown base
[ 'xpath1.0',
  'yang:hex-string',
  'boolean',
  'yang-identifier',
  'yang:zero-based-counter32',
  'yang:gauge32',
  'yang:phys-address',
  'yang:xpath1.0',
  'yang:counter32',
  'uuid',
  'hex-string',
  'ocif:interface-ref',
  'yang:counter64',
  'uint16',
  'zero-based-counter64',
  'gauge64',
  'mac-address',
  'empty',
  'int32',
  'date-and-time',
  'string',
  'timestamp',
  'uint8',
  'yang:yang-identifier',
  'int8',
  'uint64',
  'phys-address',
  'decimal64',
  'counter64',
  'yang:uuid',
  'timeticks',
  'yang:object-identifier-128',
  'counter32',
  'dotted-quad',
  'yang:mac-address',
  'uint32',
  'int16',
  'zero-based-counter32',
  'object-identifier-128',
  'yang:gauge64',
  'yang:object-identifier',
  'yang:dotted-quad',
  'yang:zero-based-counter64',
  'leafref',
  'object-identifier',
  'yang:date-and-time',
  'yang:timestamp',
  'yang:timeticks',
  'int64',
  'gauge32',
  'interface-ref']
'identityref'
'interface-type'
```

**Comment by aashaikh** [comment]
btw, the earlier fix did handle the error with policy and bgp-types modules.

**Comment by robshakir** [comment]
This is a weird one.

Essentially, one can take any identity and make it the base for any other identity -- even has its own base. So pyangbind takes every identity and makes it a potential base. However, it also tries to be nice and figure out that if no identity actually used that base, then there's no need to have it there - so it cleaned up. 

In my example here ```base-identity-ref-stacked``` uses ```base-identity-ref-one``` as a base, which uses ```base-identity-with-refs``` as a base -- so pyangbind needs to keep ```base-identity-ref-one``` as a potential base, but ```base-identity-ref-stacked``` isn't a valid base.

```javascript
    identity base-identity-with-refs;

    identity base-identity-ref-one {
        base "base-identity-with-refs";
    }
    
    identity base-identity-ref-stacked {
        base "base-identity-ref-one";
    }
```

Now, why does this matter? Because the way that pyangbind cleans up the things that aren't a base is to check whether there's any other identity specifying it with a base -- which isn't the case for ```interface-type```. If you include iana-interface-type (which I think I did last time I was checking this module, because it's included from one of the other oc-interfaces modules) then ```ocif:interface-type``` is the best guess as a base for all of the IANA interface types that pyangbind can make, and hence it keeps interface-type from ```ocif``` around.

I checked that this works for both the individual openconfig-interfaces module, and the set:

```
[~/Code/openconfig/yang/interfaces(interfaces-42*)]
(9:37 - s004) piccolo> pyang --plugindir ~/Code/pyangbind -f pybind -o /tmp/discard openconfig-interfaces.yang openconfig-if-aggregate.yang openconfig-if-ethernet.yang openconfig-if-ip.yang -p ~/Code/yang/standard/ietf/RFC 
```

BTW -- having an identity that has no other identities that reference it as a base is a no-op statement -- it equivalent to specifying an enum with no values. If you try and set this leaf it will always throw an error:

```
>>> from tmp import openconfig_interfaces
>>> i = openconfig_interfaces()
>>> i.interface.add("eth0")
>>> i.interfaces.interface.state._set_type("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'YANGBaseClass' object has no attribute 'state'
>>> i.interfaces.interface["eth0"].state._set_type("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tmp.py", line 1746, in _set_type
    raise ValueError("""type must be of a type compatible with RestrictedClassType(base_type=str, restriction_type="dict_key", restriction_arg={},)""")
ValueError: type must be of a type compatible with RestrictedClassType(base_type=str, restriction_type="dict_key", restriction_arg={},)
```

Note here that ```restriction_arg``` (which tells us what the keys that we can have are) is empty. 

This isn't a problem from a config perspective (since this is a state leaf anyway -- we need use  ```_set_type()``` rather than just ```.type = ...```) - but does mean that no backend can actually set an interface type here.

d74d83974f1efaf67c16cc2a3744616978425381 adds support for this kind of identity. It might not be a long-term thing -- perhaps pyangbind should throw an error saying that this is not a usable identity!

**Comment by robshakir** [comment]
Closing this issue as it seems resolved :) Thanks Anees.
